apiVersion: apps/v1
kind: Deployment
metadata:
  name: kjcapstone
  labels:
    app: kjcapstone
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kjcapstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: kjcapstone
    spec:
      containers:
        - image: jagadeesh8877/cloud_devops_capstone
          imagePullPolicy: Always
          name: kjcapstone
          ports:
            - containerPort: 80
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /
              port: 80